### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by fayizan**
I have read and agreed to the contributing guidelines

### CODE REVIEW

**Comment by BaumanDev** [comment]
You just flipped around the logic.

**Comment by fayizan** [comment]
yea its just showing wrong,temporary fix..lol

**Comment by m-byte918** [comment]
?

**Comment by fayizan** [comment]
**The customlb is showing wrong,check out the below image and [Agar Hero Server](http://play.ogarul.tk/?ip=178.62.126.229:443)**

wrong customlb

**After I fixed it in my server** [Asia Server](http://play.ogarul.tk/?ip=139.59.4.192:443)

corrected customlb

**Comment by segg21** [comment]
Since this is Andrew plugin, I'll wait, and let him merge, or not.

**Comment by BaumanDev** [comment]
> if (client.cells > 0) spectators++; else alive++;

That is your new code, if client has more than 0 cells (means the client is playing) spectators increase. If there is 0 cells, alive goes up. It shouldn't work that way.

**Comment by ZitroAgario** [comment]
n

**Comment by BaumanDev** [comment]
Should this be closed?

**Pull request closed without merging**
